export const OTHER_PROJECTS = [
	{
		image: "/magical-songwriter.jpg",
		alt: "Magical Songwriter - Şarkı Sözü Yazma Platformu",
		title: "Magical Songwriter - Şarkı Sözü Yazma Platformu",
		desc: "Kendi şarkı sözlerinizi kolayca yazıp düzenleyebileceğiniz, ilham verici ve kullanıcı dostu bir platform. Fikirlerinizi kaydedin, düzenleyin ve paylaşın. Müzisyenler ve söz yazarları için pratik bir dijital defter.",
		tags: [
			{ text: "HTML5", className: "bg-orange-100 text-orange-800" },
			{ text: "CSS3", className: "bg-blue-100 text-blue-800" },
			{ text: "JavaScript", className: "bg-yellow-100 text-yellow-800" },
			{ text: "TypeScript", className: "bg-teal-100 text-teal-800" },
			{ text: "Reactjs", className: "bg-green-100 text-green-800" },
			{ text: "Nextjs", className: "bg-red-100 text-red-800" },
			{ text: "React Native", className: "bg-purple-100 text-purple-800" },
		],
		link: "https://magicalsongwriter.com",
	},
	// {
	// 	image: "/peekify-insta.jpg",
	// 	alt: "PeekifyInsta - Instagram Gezinme Aracı",
	// 	title: "PeekifyInsta - Instagram Gezinme Aracı",
	// 	desc: "Instagram profil fotoğraflarını, hikayeleri, Reels'leri ve öne çıkan içerikleri ücretsiz olarak görüntülemeye yarayan platform.",
	// 	tags: [
	// 		{ text: "HTML5", className: "bg-orange-100 text-orange-800" },
	// 		{ text: "CSS3", className: "bg-blue-100 text-blue-800" },
	// 		{ text: "JavaScript", className: "bg-yellow-100 text-yellow-800" },
	// 		{ text: "TypeScript", className: "bg-teal-100 text-teal-800" },
	// 		{ text: "Reactjs", className: "bg-green-100 text-green-800" },
	// 		{ text: "Nextjs", className: "bg-red-100 text-red-800" },
	// 		{ text: "React Native", className: "bg-purple-100 text-purple-800" },
	// 		{ text: "Python", className: "bg-zinc-100 text-zinc-800" },
	// 		{ text: "Redis", className: "bg-fuchsia-100 text-fuchsia-800" },
	// 		{ text: "RabbitMQ", className: "bg-rose-100 text-rose-800" },
	// 	],
	// 	link: "https://peekifyinsta.com",
	// },
	// {
	//   image: null,
	//   alt: null,
	//   title: "Müzik Teorisi Eğitim Uygulaması",
	//   desc: "Müzik teorisi öğrenmek isteyenler için interaktif eğitim uygulaması. Akor yapıları, gamlar ve müzik notasyonu konularını içerir.",
	//   tags: [
	//     { text: "React", className: "bg-blue-100 text-blue-800" },
	//     { text: "Web Audio API", className: "bg-green-100 text-green-800" },
	//     { text: "Canvas", className: "bg-purple-100 text-purple-800" },
	//     { text: "PWA", className: "bg-red-100 text-red-800" },
	//   ],
	//   features: [
	//     "İnteraktif piyano arayüzü",
	//     "Akor ve gam tanıma egzersizleri",
	//     "Kullanıcı ilerleme takibi",
	//   ],
	//   link: "#",
	// },
]