export const OTHER_PROJECTS = [
	{
		image: "/magical-songwriter.jpg",
		alt: "Magical Songwriter - Şarkı Sözü Yazma Platformu",
		title: "Magical Songwriter - Şarkı Sözü Yazma Platformu",
		desc: "Kendi şarkı sözlerinizi kolayca yazıp düzenleyebileceğiniz, ilham verici ve kullanıcı dostu bir platform. Fikirlerinizi kaydedin, düzenleyin ve paylaşın. Müzisyenler ve söz yazarları için pratik bir dijital defter.",
		tags: [
			{ text: "HTML5", color: "orange" },
			{ text: "CSS3", color: "blue" },
			{ text: "JavaScript", color: "yellow" },
			{ text: "TypeScript", color: "teal" },
			{ text: "Reactjs", color: "green" },
			{ text: "Nextjs", color: "red" },
			{ text: "React Native", color: "purple" },
		],
		link: "https://magicalsongwriter.com",
	},
	// {
	// 	image: "/peekify-insta.jpg",
	// 	alt: "PeekifyInsta - Instagram Gezinme Aracı",
	// 	title: "PeekifyInsta - Instagram Gezinme Aracı",
	// 	desc: "Instagram profil fotoğraflarını, hikayeleri, Reels'leri ve öne çıkan içerikleri ücretsiz olarak görüntülemeye yarayan platform.",
	// 	tags: [
	// 		{ text: "HTML5", color: "orange" },
	// 		{ text: "CSS3", color: "blue" },
	// 		{ text: "JavaScript", color: "yellow" },
	// 		{ text: "TypeScript", color: "teal" },
	// 		{ text: "Reactjs", color: "green" },
	// 		{ text: "Nextjs", color: "red" },
	// 		{ text: "React Native", color: "purple" },
	// 		{ text: "Python", color: "zinc" },
	// 		{ text: "Redis", color: "fuchsia" },
	// 		{ text: "RabbitMQ", color: "rose" },
	// 	],
	// 	link: "https://peekifyinsta.com",
	// },
	// {
	//   image: null,
	//   alt: null,
	//   title: "Müzik Teorisi Eğitim Uygulaması",
	//   desc: "Müzik teorisi öğrenmek isteyenler için interaktif eğitim uygulaması. Akor yapıları, gamlar ve müzik notasyonu konularını içerir.",
	//   tags: [
	//     { text: "React", color: "blue" },
	//     { text: "Web Audio API", color: "green" },
	//     { text: "Canvas", color: "purple" },
	//     { text: "PWA", color: "red" },
	//   ],
	//   features: [
	//     "İnteraktif piyano arayüzü",
	//     "Akor ve gam tanıma egzersizleri",
	//     "Kullanıcı ilerleme takibi",
	//   ],
	//   link: "#",
	// },
]
